# roles/nvidia/tasks/main.yml
---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade system packages
  apt:
    upgrade: yes

- name: Install NVIDIA drivers and utils
  apt:
    name:
      - nvidia-driver-550-server
      - nvidia-utils-550-server
    state: present

- name: Add NVIDIA Container Toolkit GPG key
  shell: |
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

- name: Add NVIDIA Container Toolkit repository
  shell: |
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Enable experimental repository
  replace:
    path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    regexp: '^#(.*experimental.*)'
    replace: '\1'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install NVIDIA Container Toolkit
  apt:
    name: nvidia-container-toolkit
    state: present
