docker_keyrings_path: "/etc/apt/keyrings"
docker_gpg_key_path: "/etc/apt/keyrings/docker.asc"
docker_data_root: "/home/eledia-docker"
docker_home: "/home/docker"
docker_repo_url: "https://download.docker.com/linux/ubuntu"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
docker_old_packages:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc
docker_prerequisites:
  - ca-certificates
  - curl
docker_daemon_config:
  data-root: "{{ docker_data_root }}"
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
